name: Build and Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'  # каждые 12 часов

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install deps
        working-directory: "aff_pages_automation (1)"
        run: npm ci

      - name: Build site
        working-directory: "aff_pages_automation (1)"
        env:
          SHEET_CSV_URL: ${{ secrets.SHEET_CSV_URL }}
          CLOUDINARY_CLOUD: ${{ secrets.CLOUDINARY_CLOUD }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "aff_pages_automation (1)/dist"

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
